AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla para lanzar una instancia EC2 y habilitar SSH dentro de una VPC y conexión con un S3

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: Must be the VPC Id of an existing Virtual Private Cloud.
  
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
    ConstraintDescription: Must be a list of at least two existing subnets associated with at least two different availability zones.

  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: Nombre del SSH KeyPair
    ConstraintDescription: Provide the name of an existing SSH key pair

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b70fa74e45c3917
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: lab16

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: DMZSecurityGroup
      GroupDescription: Habilitar acceso SSH via puerto 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceID:
    Description: Instance ID
    Value: !Ref MyEC2Instance
